[package]
name = "mogidb"
version = "0.1.0"
edition = "2024"
default-run = "mogidb"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
axum-valid = { version = "0.24", default-features = false, features = ["garde", "basic"] }
derive_more = { workspace = true, features = ["deref", "display", "from"] }
dotenv = "0.15.0"
eyre = "0.6.12"
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = { workspace = true }
mogidb-model = { workspace = true }
tokio = { version = "1.52.3", features = ["macros", "rt", "rt-multi-thread", "net"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
garde = { version = "0.22", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["chrono", "runtime-tokio-rustls", "sqlite"] }
color-eyre = "0.6.5"
chrono = { workspace = true, features = ["serde"] }
num_enum = { workspace = true }
bytemuck = { workspace = true, features = ["derive", "min_const_generics"] }
papaya = "0.2.4"
base16 = "0.2.1"
serde_json = "1.0.149"
serde_with = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
clap = { version = "4", features = ["derive"] }
serde_norway = "0.9.42"
rand = "0.10.2"

[workspace]
resolver = "3"
members = ["model"]

[workspace.dependencies]
bitflags = "2"
num_enum = "0.7"
chrono = "0.4"
derive_more = "2"
mogidb-model = { path = "./model" }
bytemuck = "1"
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
serde_with = "3"
utoipa = { version = "5", features = ["chrono", "repr"] }
utoipa-swagger-ui = "9"
